[workspace]
members = ["common", "order-service", "user-service"]
resolver = "2"

[workspace.dependencies]
axum = "0.7.4"
common = { path = "common" }
serde = { version = "1.0.197", features = ["derive"] }
shuttle-axum = "0.42.0"
shuttle-runtime = "0.42.0"
tower-jwt = "0.2.1"
